// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	logcollectorv1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	versioned "harmonycloud.cn/log-collector/pkg/client/clientset/versioned"
	internalinterfaces "harmonycloud.cn/log-collector/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "harmonycloud.cn/log-collector/pkg/client/listers/logcollector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HostLogCollectionRuleInformer provides access to a shared informer and lister for
// HostLogCollectionRules.
type HostLogCollectionRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HostLogCollectionRuleLister
}

type hostLogCollectionRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewHostLogCollectionRuleInformer constructs a new informer for HostLogCollectionRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHostLogCollectionRuleInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHostLogCollectionRuleInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredHostLogCollectionRuleInformer constructs a new informer for HostLogCollectionRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHostLogCollectionRuleInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LogcollectorV1alpha1().HostLogCollectionRules().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LogcollectorV1alpha1().HostLogCollectionRules().Watch(context.TODO(), options)
			},
		},
		&logcollectorv1alpha1.HostLogCollectionRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *hostLogCollectionRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHostLogCollectionRuleInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hostLogCollectionRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&logcollectorv1alpha1.HostLogCollectionRule{}, f.defaultInformer)
}

func (f *hostLogCollectionRuleInformer) Lister() v1alpha1.HostLogCollectionRuleLister {
	return v1alpha1.NewHostLogCollectionRuleLister(f.Informer().GetIndexer())
}
