// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "harmonycloud.cn/log-collector/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// HostLogCollectionRules returns a HostLogCollectionRuleInformer.
	HostLogCollectionRules() HostLogCollectionRuleInformer
	// LogCollectionRules returns a LogCollectionRuleInformer.
	LogCollectionRules() LogCollectionRuleInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// HostLogCollectionRules returns a HostLogCollectionRuleInformer.
func (v *version) HostLogCollectionRules() HostLogCollectionRuleInformer {
	return &hostLogCollectionRuleInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// LogCollectionRules returns a LogCollectionRuleInformer.
func (v *version) LogCollectionRules() LogCollectionRuleInformer {
	return &logCollectionRuleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
