// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	logcollectorv1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	versioned "harmonycloud.cn/log-collector/pkg/client/clientset/versioned"
	internalinterfaces "harmonycloud.cn/log-collector/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "harmonycloud.cn/log-collector/pkg/client/listers/logcollector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// LogCollectionRuleInformer provides access to a shared informer and lister for
// LogCollectionRules.
type LogCollectionRuleInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LogCollectionRuleLister
}

type logCollectionRuleInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewLogCollectionRuleInformer constructs a new informer for LogCollectionRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLogCollectionRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredLogCollectionRuleInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredLogCollectionRuleInformer constructs a new informer for LogCollectionRule type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLogCollectionRuleInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LogcollectorV1alpha1().LogCollectionRules(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LogcollectorV1alpha1().LogCollectionRules(namespace).Watch(context.TODO(), options)
			},
		},
		&logcollectorv1alpha1.LogCollectionRule{},
		resyncPeriod,
		indexers,
	)
}

func (f *logCollectionRuleInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLogCollectionRuleInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *logCollectionRuleInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&logcollectorv1alpha1.LogCollectionRule{}, f.defaultInformer)
}

func (f *logCollectionRuleInformer) Lister() v1alpha1.LogCollectionRuleLister {
	return v1alpha1.NewLogCollectionRuleLister(f.Informer().GetIndexer())
}
