// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// HostLogCollectionRuleListerExpansion allows custom methods to be added to
// HostLogCollectionRuleLister.
type HostLogCollectionRuleListerExpansion interface{}

// LogCollectionRuleListerExpansion allows custom methods to be added to
// LogCollectionRuleLister.
type LogCollectionRuleListerExpansion interface{}

// LogCollectionRuleNamespaceListerExpansion allows custom methods to be added to
// LogCollectionRuleNamespaceLister.
type LogCollectionRuleNamespaceListerExpansion interface{}
