// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// LogCollectionRuleLister helps list LogCollectionRules.
// All objects returned here must be treated as read-only.
type LogCollectionRuleLister interface {
	// List lists all LogCollectionRules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LogCollectionRule, err error)
	// LogCollectionRules returns an object that can list and get LogCollectionRules.
	LogCollectionRules(namespace string) LogCollectionRuleNamespaceLister
	LogCollectionRuleListerExpansion
}

// logCollectionRuleLister implements the LogCollectionRuleLister interface.
type logCollectionRuleLister struct {
	indexer cache.Indexer
}

// NewLogCollectionRuleLister returns a new LogCollectionRuleLister.
func NewLogCollectionRuleLister(indexer cache.Indexer) LogCollectionRuleLister {
	return &logCollectionRuleLister{indexer: indexer}
}

// List lists all LogCollectionRules in the indexer.
func (s *logCollectionRuleLister) List(selector labels.Selector) (ret []*v1alpha1.LogCollectionRule, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LogCollectionRule))
	})
	return ret, err
}

// LogCollectionRules returns an object that can list and get LogCollectionRules.
func (s *logCollectionRuleLister) LogCollectionRules(namespace string) LogCollectionRuleNamespaceLister {
	return logCollectionRuleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// LogCollectionRuleNamespaceLister helps list and get LogCollectionRules.
// All objects returned here must be treated as read-only.
type LogCollectionRuleNamespaceLister interface {
	// List lists all LogCollectionRules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.LogCollectionRule, err error)
	// Get retrieves the LogCollectionRule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.LogCollectionRule, error)
	LogCollectionRuleNamespaceListerExpansion
}

// logCollectionRuleNamespaceLister implements the LogCollectionRuleNamespaceLister
// interface.
type logCollectionRuleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all LogCollectionRules in the indexer for a given namespace.
func (s logCollectionRuleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.LogCollectionRule, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.LogCollectionRule))
	})
	return ret, err
}

// Get retrieves the LogCollectionRule from the indexer for a given namespace and name.
func (s logCollectionRuleNamespaceLister) Get(name string) (*v1alpha1.LogCollectionRule, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("logcollectionrule"), name)
	}
	return obj.(*v1alpha1.LogCollectionRule), nil
}
