// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	scheme "harmonycloud.cn/log-collector/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HostLogCollectionRulesGetter has a method to return a HostLogCollectionRuleInterface.
// A group's client should implement this interface.
type HostLogCollectionRulesGetter interface {
	HostLogCollectionRules() HostLogCollectionRuleInterface
}

// HostLogCollectionRuleInterface has methods to work with HostLogCollectionRule resources.
type HostLogCollectionRuleInterface interface {
	Create(ctx context.Context, hostLogCollectionRule *v1alpha1.HostLogCollectionRule, opts v1.CreateOptions) (*v1alpha1.HostLogCollectionRule, error)
	Update(ctx context.Context, hostLogCollectionRule *v1alpha1.HostLogCollectionRule, opts v1.UpdateOptions) (*v1alpha1.HostLogCollectionRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HostLogCollectionRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HostLogCollectionRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostLogCollectionRule, err error)
	HostLogCollectionRuleExpansion
}

// hostLogCollectionRules implements HostLogCollectionRuleInterface
type hostLogCollectionRules struct {
	client rest.Interface
}

// newHostLogCollectionRules returns a HostLogCollectionRules
func newHostLogCollectionRules(c *LogcollectorV1alpha1Client) *hostLogCollectionRules {
	return &hostLogCollectionRules{
		client: c.RESTClient(),
	}
}

// Get takes name of the hostLogCollectionRule, and returns the corresponding hostLogCollectionRule object, and an error if there is any.
func (c *hostLogCollectionRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HostLogCollectionRule, err error) {
	result = &v1alpha1.HostLogCollectionRule{}
	err = c.client.Get().
		Resource("hostlogcollectionrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HostLogCollectionRules that match those selectors.
func (c *hostLogCollectionRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HostLogCollectionRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HostLogCollectionRuleList{}
	err = c.client.Get().
		Resource("hostlogcollectionrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hostLogCollectionRules.
func (c *hostLogCollectionRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("hostlogcollectionrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hostLogCollectionRule and creates it.  Returns the server's representation of the hostLogCollectionRule, and an error, if there is any.
func (c *hostLogCollectionRules) Create(ctx context.Context, hostLogCollectionRule *v1alpha1.HostLogCollectionRule, opts v1.CreateOptions) (result *v1alpha1.HostLogCollectionRule, err error) {
	result = &v1alpha1.HostLogCollectionRule{}
	err = c.client.Post().
		Resource("hostlogcollectionrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hostLogCollectionRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hostLogCollectionRule and updates it. Returns the server's representation of the hostLogCollectionRule, and an error, if there is any.
func (c *hostLogCollectionRules) Update(ctx context.Context, hostLogCollectionRule *v1alpha1.HostLogCollectionRule, opts v1.UpdateOptions) (result *v1alpha1.HostLogCollectionRule, err error) {
	result = &v1alpha1.HostLogCollectionRule{}
	err = c.client.Put().
		Resource("hostlogcollectionrules").
		Name(hostLogCollectionRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hostLogCollectionRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hostLogCollectionRule and deletes it. Returns an error if one occurs.
func (c *hostLogCollectionRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("hostlogcollectionrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hostLogCollectionRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("hostlogcollectionrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hostLogCollectionRule.
func (c *hostLogCollectionRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostLogCollectionRule, err error) {
	result = &v1alpha1.HostLogCollectionRule{}
	err = c.client.Patch(pt).
		Resource("hostlogcollectionrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
