// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	v1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	"harmonycloud.cn/log-collector/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type LogcollectorV1alpha1Interface interface {
	RESTClient() rest.Interface
	HostLogCollectionRulesGetter
	LogCollectionRulesGetter
}

// LogcollectorV1alpha1Client is used to interact with features provided by the logcollector.harmonycloud.cn group.
type LogcollectorV1alpha1Client struct {
	restClient rest.Interface
}

func (c *LogcollectorV1alpha1Client) HostLogCollectionRules() HostLogCollectionRuleInterface {
	return newHostLogCollectionRules(c)
}

func (c *LogcollectorV1alpha1Client) LogCollectionRules(namespace string) LogCollectionRuleInterface {
	return newLogCollectionRules(c, namespace)
}

// NewForConfig creates a new LogcollectorV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*LogcollectorV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new LogcollectorV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*LogcollectorV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &LogcollectorV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new LogcollectorV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *LogcollectorV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new LogcollectorV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *LogcollectorV1alpha1Client {
	return &LogcollectorV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *LogcollectorV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
