// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	scheme "harmonycloud.cn/log-collector/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LogCollectionRulesGetter has a method to return a LogCollectionRuleInterface.
// A group's client should implement this interface.
type LogCollectionRulesGetter interface {
	LogCollectionRules(namespace string) LogCollectionRuleInterface
}

// LogCollectionRuleInterface has methods to work with LogCollectionRule resources.
type LogCollectionRuleInterface interface {
	Create(ctx context.Context, logCollectionRule *v1alpha1.LogCollectionRule, opts v1.CreateOptions) (*v1alpha1.LogCollectionRule, error)
	Update(ctx context.Context, logCollectionRule *v1alpha1.LogCollectionRule, opts v1.UpdateOptions) (*v1alpha1.LogCollectionRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.LogCollectionRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.LogCollectionRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogCollectionRule, err error)
	LogCollectionRuleExpansion
}

// logCollectionRules implements LogCollectionRuleInterface
type logCollectionRules struct {
	client rest.Interface
	ns     string
}

// newLogCollectionRules returns a LogCollectionRules
func newLogCollectionRules(c *LogcollectorV1alpha1Client, namespace string) *logCollectionRules {
	return &logCollectionRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the logCollectionRule, and returns the corresponding logCollectionRule object, and an error if there is any.
func (c *logCollectionRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LogCollectionRule, err error) {
	result = &v1alpha1.LogCollectionRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logcollectionrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LogCollectionRules that match those selectors.
func (c *logCollectionRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LogCollectionRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.LogCollectionRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logcollectionrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested logCollectionRules.
func (c *logCollectionRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("logcollectionrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a logCollectionRule and creates it.  Returns the server's representation of the logCollectionRule, and an error, if there is any.
func (c *logCollectionRules) Create(ctx context.Context, logCollectionRule *v1alpha1.LogCollectionRule, opts v1.CreateOptions) (result *v1alpha1.LogCollectionRule, err error) {
	result = &v1alpha1.LogCollectionRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("logcollectionrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logCollectionRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a logCollectionRule and updates it. Returns the server's representation of the logCollectionRule, and an error, if there is any.
func (c *logCollectionRules) Update(ctx context.Context, logCollectionRule *v1alpha1.LogCollectionRule, opts v1.UpdateOptions) (result *v1alpha1.LogCollectionRule, err error) {
	result = &v1alpha1.LogCollectionRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("logcollectionrules").
		Name(logCollectionRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logCollectionRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the logCollectionRule and deletes it. Returns an error if one occurs.
func (c *logCollectionRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logcollectionrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *logCollectionRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logcollectionrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched logCollectionRule.
func (c *logCollectionRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogCollectionRule, err error) {
	result = &v1alpha1.LogCollectionRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("logcollectionrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
