// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostLogCollectionRules implements HostLogCollectionRuleInterface
type FakeHostLogCollectionRules struct {
	Fake *FakeLogcollectorV1alpha1
}

var hostlogcollectionrulesResource = schema.GroupVersionResource{Group: "logcollector.harmonycloud.cn", Version: "v1alpha1", Resource: "hostlogcollectionrules"}

var hostlogcollectionrulesKind = schema.GroupVersionKind{Group: "logcollector.harmonycloud.cn", Version: "v1alpha1", Kind: "HostLogCollectionRule"}

// Get takes name of the hostLogCollectionRule, and returns the corresponding hostLogCollectionRule object, and an error if there is any.
func (c *FakeHostLogCollectionRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HostLogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(hostlogcollectionrulesResource, name), &v1alpha1.HostLogCollectionRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostLogCollectionRule), err
}

// List takes label and field selectors, and returns the list of HostLogCollectionRules that match those selectors.
func (c *FakeHostLogCollectionRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HostLogCollectionRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(hostlogcollectionrulesResource, hostlogcollectionrulesKind, opts), &v1alpha1.HostLogCollectionRuleList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HostLogCollectionRuleList{ListMeta: obj.(*v1alpha1.HostLogCollectionRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.HostLogCollectionRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostLogCollectionRules.
func (c *FakeHostLogCollectionRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(hostlogcollectionrulesResource, opts))
}

// Create takes the representation of a hostLogCollectionRule and creates it.  Returns the server's representation of the hostLogCollectionRule, and an error, if there is any.
func (c *FakeHostLogCollectionRules) Create(ctx context.Context, hostLogCollectionRule *v1alpha1.HostLogCollectionRule, opts v1.CreateOptions) (result *v1alpha1.HostLogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(hostlogcollectionrulesResource, hostLogCollectionRule), &v1alpha1.HostLogCollectionRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostLogCollectionRule), err
}

// Update takes the representation of a hostLogCollectionRule and updates it. Returns the server's representation of the hostLogCollectionRule, and an error, if there is any.
func (c *FakeHostLogCollectionRules) Update(ctx context.Context, hostLogCollectionRule *v1alpha1.HostLogCollectionRule, opts v1.UpdateOptions) (result *v1alpha1.HostLogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(hostlogcollectionrulesResource, hostLogCollectionRule), &v1alpha1.HostLogCollectionRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostLogCollectionRule), err
}

// Delete takes name of the hostLogCollectionRule and deletes it. Returns an error if one occurs.
func (c *FakeHostLogCollectionRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(hostlogcollectionrulesResource, name, opts), &v1alpha1.HostLogCollectionRule{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostLogCollectionRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(hostlogcollectionrulesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HostLogCollectionRuleList{})
	return err
}

// Patch applies the patch and returns the patched hostLogCollectionRule.
func (c *FakeHostLogCollectionRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostLogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(hostlogcollectionrulesResource, name, pt, data, subresources...), &v1alpha1.HostLogCollectionRule{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostLogCollectionRule), err
}
