// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "harmonycloud.cn/log-collector/pkg/apis/logcollector/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLogCollectionRules implements LogCollectionRuleInterface
type FakeLogCollectionRules struct {
	Fake *FakeLogcollectorV1alpha1
	ns   string
}

var logcollectionrulesResource = schema.GroupVersionResource{Group: "logcollector.harmonycloud.cn", Version: "v1alpha1", Resource: "logcollectionrules"}

var logcollectionrulesKind = schema.GroupVersionKind{Group: "logcollector.harmonycloud.cn", Version: "v1alpha1", Kind: "LogCollectionRule"}

// Get takes name of the logCollectionRule, and returns the corresponding logCollectionRule object, and an error if there is any.
func (c *FakeLogCollectionRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(logcollectionrulesResource, c.ns, name), &v1alpha1.LogCollectionRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogCollectionRule), err
}

// List takes label and field selectors, and returns the list of LogCollectionRules that match those selectors.
func (c *FakeLogCollectionRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LogCollectionRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(logcollectionrulesResource, logcollectionrulesKind, c.ns, opts), &v1alpha1.LogCollectionRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LogCollectionRuleList{ListMeta: obj.(*v1alpha1.LogCollectionRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.LogCollectionRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested logCollectionRules.
func (c *FakeLogCollectionRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(logcollectionrulesResource, c.ns, opts))

}

// Create takes the representation of a logCollectionRule and creates it.  Returns the server's representation of the logCollectionRule, and an error, if there is any.
func (c *FakeLogCollectionRules) Create(ctx context.Context, logCollectionRule *v1alpha1.LogCollectionRule, opts v1.CreateOptions) (result *v1alpha1.LogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(logcollectionrulesResource, c.ns, logCollectionRule), &v1alpha1.LogCollectionRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogCollectionRule), err
}

// Update takes the representation of a logCollectionRule and updates it. Returns the server's representation of the logCollectionRule, and an error, if there is any.
func (c *FakeLogCollectionRules) Update(ctx context.Context, logCollectionRule *v1alpha1.LogCollectionRule, opts v1.UpdateOptions) (result *v1alpha1.LogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(logcollectionrulesResource, c.ns, logCollectionRule), &v1alpha1.LogCollectionRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogCollectionRule), err
}

// Delete takes name of the logCollectionRule and deletes it. Returns an error if one occurs.
func (c *FakeLogCollectionRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(logcollectionrulesResource, c.ns, name, opts), &v1alpha1.LogCollectionRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLogCollectionRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(logcollectionrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LogCollectionRuleList{})
	return err
}

// Patch applies the patch and returns the patched logCollectionRule.
func (c *FakeLogCollectionRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LogCollectionRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(logcollectionrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.LogCollectionRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LogCollectionRule), err
}
