// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "harmonycloud.cn/log-collector/pkg/client/clientset/versioned/typed/logcollector/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeLogcollectorV1alpha1 struct {
	*testing.Fake
}

func (c *FakeLogcollectorV1alpha1) HostLogCollectionRules() v1alpha1.HostLogCollectionRuleInterface {
	return &FakeHostLogCollectionRules{c}
}

func (c *FakeLogcollectorV1alpha1) LogCollectionRules(namespace string) v1alpha1.LogCollectionRuleInterface {
	return &FakeLogCollectionRules{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeLogcollectorV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
